package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Game search working")
    void generatedTest() {
        step("Open https://www.oddsking.com/", () -> {
            step("// todo: just add selenium action");
        });

        step("Print \"game\" text into \"Search for a game\" text field", () -> {
            step("// todo: just add selenium action");
        });

        step("Click enter", () -> {
            step("// todo: just add selenium action");
        });

        step("\"3 games found for you...\" text appears as a result", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://www.oddsking.com/'", () ->
            open("https://www.oddsking.com/"));

        step("Page title should have text 'OddsKing - Play popular arcade gambling games online at OddsKing'", () -> {
            String expectedTitle = "OddsKing - Play popular arcade gambling games online at OddsKing";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://www.oddsking.com/'", () ->
            open("https://www.oddsking.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}